languageCode = "en-us"

theme = "myTheme"
baseURL = "https://condescending-torvalds-7033e4.netlify.app/"
title = "Dzianis Samokhin"


## Profile Configurations
[params.profile]
  portrait = "/images/main.jpg"
  firstname = "Dzianis ( Denis )"
  lastname = "Samokhin"
  title = "Software Engineer / Web Developer"
  bio = """Dzianis Samokhin
  """

## Contacts Configurations
[params.contacts]
  email = "denis1882531@gmail.com"
  github = "GonEbal"
  linkedin = "denis-samokhin"
  instagram = "samokhin_official"
  stackoverflow = "14852241"


## Actions Configurations
[params.actions]
  name = "Review My CV"
  url = "https://en.wikipedia.org/wiki/Virtual_reality"


## Footer Configurations
[params.footer]
  copyright = "© 2021 Dzianis Samokhin. [GitHub](https://github.com/GonEbal)."

