languageCode = "en-us"

theme = "awesome-identity"
baseURL = "https://condescending-torvalds-7033e4.netlify.app/"
title = "Dzianis Samokhin"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Dzianis ( Denis )"
  lastname = "Samokhin"
  title = "Software Engineer / Web Developer"
  bio = """Dzianis Samokhin brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.
  """

## Contacts Configurations
[params.contacts]
  email = "denis1882531@example.com"
  github = "GonEbal"
  linkedin = "denis-samokhin"
  instagram = "samokhin_official"
  stackoverflow = "14852241"


## Footer Configurations
[params.footer]
  copyright = "© 2021 Dzianis Samokhin. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true

